### ISSUE TITLE
Re-opened Shuttle skipped ETH blocks / did not credit unwrapped tokens

### ISSUE THREAD

**Issue by StrathCole** [terra-money/shuttle#105] opened 2024-08-27 15:19 UTC
Several transactions have not been processed (correctly) by the relayer. See below comments for updated transaction list.

**Comment by kwyzgol** [comment] 2024-08-28 10:05
0xbb7a447e8bec502bd377c7eac7a64dcc87ef87128cd6c57731777679f16414fe
0x9045a7db6908cb3d59e17b0a3bd463b02ca8a31e09b1807cac333b78001e918c

These two from today also look like they were skipped.

**Comment by StrathCole** [comment] 2024-08-28 14:03
Further big missed transactions popped up (the 5M in the screenshot went through)

0x61379fd0034b167de977f143aa7f97b3ba01bae80be62b981d887f7497973d49
0xdfa6c605bd7aba2838c876486eff0f1342af5136db7b08fcfd80c524d435797c

![grafik](https://github.com/user-attachments/assets/6fa52949-3194-46fd-b2d4-ee43b0787557)

**Comment by javiersuweijie** [comment] 2024-08-28 14:26
These transactions failed with an error of something similar to `5 - spendable balance 128417274807uluna is smaller than 133417274806uluna: insufficient funds: insufficient funds`

The cause is an incorrect handling of tax for multi msg transactions. The fix has been deployed and we will make sure everything is working. We've reconciled the transactions below and will be manually sending the txs out.

|EthTxHash                                                         |Recipient                                   |Amount|Asset|
|------------------------------------------------------------------|--------------------------------------------|------|-----|
|0x045d00df5ef2e321a396fc2c2873d336f937bfacd5c312e21a46404f23657eef|terra172nxjfv764sqwn94qp04wnmv8szcq3gszxl6f8|1500000|LUNA |
|0x07cd072c8ae60b95cecb1728b9e87579a9e5e6cb033e675ddb4e8ec5063bd101|terra1sl3k9aq60rej58c387l8czdj4085u6732ymyjz|150   |LUNA |
|0x07d7eb03330addf058f8872a43818195ffb152aab6b110111fabd1c6d3e196b3|terra1hwa6428ltq9spz3msmjw5jkrv3erg4cay8d6ra|12132.77342|LUNA |
|0x14fd8a62ab8236f75017e4f7c9649ff3034a9d137a795921d48f5dc0a6048eed|terra1ekntas3us2alhf4qwkzqj4tzg6v7tcx69h9auw|2732247.933|LUNA |
|0x255376efd2fb969cc64c45a1a9f903eeffb2454fe950b8cc219b3a80decbb239|terra1825w0yq9989hedx3xcwnxe3rw2x60k36eejv6n|100000|LUNA |
|0x2e8324dfc40063c96abf7c05f71e8308b0c21a2399ec6deb12a9a2a035c94d1e|terra1xvu5dtfeh40nx47qwx8s0mhzu4w5l5p09mzv7e|888   |LUNA |
|0x445f7ad25aa0ad80662539e47cbc18830debd72ba197d5b9e1ef3149d3a906d0|terra13ynv6ynhex7m9r5q6uhtshjuugufdl583j3pqw|34497480.68|LUNA |
|0x4e488af1a1fba36194eb54e8a0e0704fe86a7f1408dbfe615ce979f6ee171391|terra13ynv6ynhex7m9r5q6uhtshjuugufdl583j3pqw|100   |LUNA |
|0x61379fd0034b167de977f143aa7f97b3ba01bae80be62b981d887f7497973d49|terra1825w0yq9989hedx3xcwnxe3rw2x60k36eejv6n|156864259.9|LUNA |
|0x664a686ce40adcd708590666c846ecff613d880dc610ae52652cac52915c5d9d|terra1f6j6jcqjfk3gxg6kfd0v5ht782y625u349kqqz|54550606.99|LUNA |
|0x69b4c7a60d9da255d806a7fbd4dc4e935f72bde0441ffae9a354e0dba99cfa00|terra1sl3k9aq60rej58c387l8czdj4085u6732ymyjz|101   |LUNA |
|0x6b124da2174032b9a6a479886c86364e2b96b397ccbafac8d8001e93b42d1afc|terra1u46g3tt03q4ufdjuq7vtajakncv5nq4r07zfh3|20000 |LUNA |
|0x6e90d29275fc44153a9404977ff9b97b526625e90740a9157b4eeda8ff9305c6|terra160rnl9gdel8kfm6jxapqny38eej8xusl9y2dmj|6000000|LUNA |
|0x6f601419e997f256a76045a770de4748e2b24b9741275137113bcc0b650f7fa5|terra1sl3k9aq60rej58c387l8czdj4085u6732ymyjz|137   |LUNA |
|0x70210580c6cfcf168b71e34830b987f84d5855774ec346b8fb49e1e7bd5ca287|terra1ekntas3us2alhf4qwkzqj4tzg6v7tcx69h9auw|2598893.73|LUNA |
|0x778b969ce17aef509a5c76f719e7794c30c6934a897cf768c2d5677e78bf84ff|terra1sl3k9aq60rej58c387l8czdj4085u6732ymyjz|105   |LUNA |
|0x80ef89108ae764d8d47398a686c4d8441a9a79060797de683cf9fa00af8d13a9|terra1lru2elwthtalmp5prg0l0yxeqds24dx7vf0u9c|20000 |LUNA |
|0x878e8cb24caab48e1a75c6793cafd5a2f8e2f5c8f6f033269ed3b1120882ff20|terra1dy8snrujmsmz5j3v0dhftj5l2j2m6pfrdj7mxx|100000|LUNA |
|0x8f0bf636d8bf325b5325c52645c4f82f7d2ab97d3c84bccc6db49596ec205f63|terra1sl3k9aq60rej58c387l8czdj4085u6732ymyjz|102   |LUNA |
|0x9045a7db6908cb3d59e17b0a3bd463b02ca8a31e09b1807cac333b78001e918c|terra13ynv6ynhex7m9r5q6uhtshjuugufdl583j3pqw|32354318.7|LUNA |
|0x95aa2e085d9833c78c2c7177568f5b29b763ca3bf3631b0b383c91d226a410a5|terra1f6j6jcqjfk3gxg6kfd0v5ht782y625u349kqqz|51005990.83|LUNA |
|0x9863166cb3d790fec91ead55d9a295dedca15aaf243ff296870a0e181cd93aee|terra1f6j6jcqjfk3gxg6kfd0v5ht782y625u349kqqz|261149859.1|LUNA |
|0x98a5514cb879f242e15b8778ee3c800d907234b0097064d70bcce31d702c2306|terra172nxjfv764sqwn94qp04wnmv8szcq3gszxl6f8|15250000|LUNA |
|0xa6d5d9b9826aafd6e4f3067c2bc56d9bb1ccf2dfaf5c439d25c306833a907111|terra1sl3k9aq60rej58c387l8czdj4085u6732ymyjz|130   |LUNA |
|0xa7d9e76cd644cf09d5291dd9cee72f0060d57a2680077ff4f116707bca51113c|terra1ekntas3us2alhf4qwkzqj4tzg6v7tcx69h9auw|4646871.502|LUNA |
|0xbb7a447e8bec502bd377c7eac7a64dcc87ef87128cd6c57731777679f16414fe|terra1he2pnmjvrfrd5ans7y95jwh34epwwzp3hdqers|1000000|LUNA |
|0xc36d796ab025e2b71cc42d12d63ececfa0454f078ea740aa751bd11fbfa5fb72|terra1u46g3tt03q4ufdjuq7vtajakncv5nq4r07zfh3|400000|LUNA |
|0xc68103fbc943d9253f19739ba1d784ed08d413ee415da2d6e6d1b41c2d291471|terra1sl3k9aq60rej58c387l8czdj4085u6732ymyjz|38815814.84|LUNA |
|0xd2384bb9a5fdcdb89b3834af4f5bf4b7a3aeb520435c70a865e102f9cb0b90bd|terra19uhq5javpaevqtfns8t52etf6dln7w52v52263|1000000|LUNA |
|0xd796f4b1cac445dd40cba496616e36a0ada2e5b3f6ae1a027cb67563eb96ec0c|terra1mjspk200psy42k6l5hqkchmkv39kw4wct39atx|100000|LUNA |
|0xda147ada90f14553ebd9d739cad83a38b06902a1709d476b5498b82e0a0fdc6f|terra19uxzge89wnrkhmmeqk4zk8f9laq49j3x7zjdh0|100000|LUNA |
|0xdfa6c605bd7aba2838c876486eff0f1342af5136db7b08fcfd80c524d435797c|terra1jyrgt5cesc23dre3lw0tmzpwn8kzz3t9prl9r7|968473894.1|LUNA |
|0xe5bd1484cac07a5c75111be41e55baeff2271fcad4dd1133c2dbd882b0966325|terra1dknc3y37w8q2ydna93um6d6wqthyuuptnykcs8|12451.64977|LUNA |
|0xec8fc8ecdd6da663f1442ae184349a0517dbdebd74e5708c9676c3c5f9964d36|terra1eck67jpz0tmnchz28ezsj40awlspycs96hrk38|1395690.951|LUNA |
|0xef0651573612a86863e31d8184836b1eec7ab7c4ad2fe34090f91f927c43d057|terra1he2pnmjvrfrd5ans7y95jwh34epwwzp3hdqers|1000000|LUNA |
|0xf42603538f45d297b8691d0248089a1a23428a744d056f102046a502ed035600|terra13yxhrk08qvdf5zdc9ss5mwsg5sf7zva9xrgwgc|777   |LUNA |
|0xf60fec61623df261972927edaf89379780cf21ef2a7890e93a7e4a627240654e|terra1eck67jpz0tmnchz28ezsj40awlspycs96hrk38|19841858.55|LUNA |

**Comment by StrathCole** [comment] 2024-08-28 14:28
> These transactions failed with an error of something similar to `5 - spendable balance 128417274807uluna is smaller than 133417274806uluna: insufficient funds: insufficient funds`
> 
> The cause is an incorrect handling of tax for multi msg transactions. The fix has been deployed and we will make sure everything is working. We've reconciled the transactions below and will be manually sending the txs out.

Wait a sec please, it seems some of those in your list have gone through. I will recheck.

**Comment by javiersuweijie** [comment] 2024-08-28 14:34
These two have gone through. We will do a check again to make sure before we relay these transactions. 

|                                                                  |                                            |     |    |                                                                |
|------------------------------------------------------------------|--------------------------------------------|-----|----|----------------------------------------------------------------|
|0x95aa2e085d9833c78c2c7177568f5b29b763ca3bf3631b0b383c91d226a410a5|terra1f6j6jcqjfk3gxg6kfd0v5ht782y625u349kqqz|51005990.83|LUNA|FBA653F19451DD4CA5E67462F916448371FC065C30B0C6923908F4BAA3AD543E|
|0xd796f4b1cac445dd40cba496616e36a0ada2e5b3f6ae1a027cb67563eb96ec0c|terra1mjspk200psy42k6l5hqkchmkv39kw4wct39atx|100000|LUNA|1F7F85581A27DD4957A5639DFE0F414F9B940220C49115B5F74D86A0CE55CC3C|

**Comment by StrathCole** [comment] 2024-08-28 14:37
> these two have gone through
> 				
Yes, but I didn't list them, or did I? In your list the decimal is shifted by 1 I think. The numbers are all too low by 10x.  
Also you have much more txs in your list than I had in mine :thinking:

**Comment by tripoxlol** [comment] 2024-08-28 14:40
The 968,473,894 wluna transaction is mine.

was sent to wallet terra1jyrgt5cesc23dre3lw0tmzpwn8kzz3t9prl9r7

I'm even feeling sick, afraid of losing everything.

Transaction Hash: 0xdfa6c605bd7aba2838c876486eff0f1342af5136db7b08fcfd80c524d435797c

please help me!

**Comment by StrathCole** [comment] 2024-08-28 14:40
@javiersuweijie 
These are the txs in your list that I didn't see getting stuck. But maybe I missed/overlooked some.
```
0x255376efd2fb969cc64c45a1a9f903eeffb2454fe950b8cc219b3a80decbb239 
0x6b124da2174032b9a6a479886c86364e2b96b397ccbafac8d8001e93b42d1afc 
0x778b969ce17aef509a5c76f719e7794c30c6934a897cf768c2d5677e78bf84ff 
0x95aa2e085d9833c78c2c7177568f5b29b763ca3bf3631b0b383c91d226a410a5 
0x98a5514cb879f242e15b8778ee3c800d907234b0097064d70bcce31d702c2306 
0xa7d9e76cd644cf09d5291dd9cee72f0060d57a2680077ff4f116707bca51113c 
0xc36d796ab025e2b71cc42d12d63ececfa0454f078ea740aa751bd11fbfa5fb72 
0xda147ada90f14553ebd9d739cad83a38b06902a1709d476b5498b82e0a0fdc6f 
0xec8fc8ecdd6da663f1442ae184349a0517dbdebd74e5708c9676c3c5f9964d36 
0xf60fec61623df261972927edaf89379780cf21ef2a7890e93a7e4a627240654e  
```

**Comment by StrathCole** [comment] 2024-08-28 14:43
Ah okay, some are from much earlier. I didn't check anything before yesterday.

**Comment by StrathCole** [comment] 2024-08-28 14:45
@javiersuweijie okay, then your list looks fine except the two that you already mentioned that went through (0x95 and 0xd7) and the amounts. Thank you for looking into this.

**Comment by javiersuweijie** [comment] 2024-08-28 14:47
@StrathCole Thanks for your help. 

@tripoxlol Give us some time < 24h to sort it out and we will re-publish the missing txns.

**Comment by tripoxlol** [comment] 2024-08-28 16:29
Transaction Completed 
Transaction Hash: 0xdfa6c605bd7aba2838c876486eff0f1342af5136db7b08fcfd80c524d435797c
 
Thanks !

special thanks to @StrathCole @javiersuweijie & @vegas

**Closed as completed** 2024-09-02 09:01 UTC

**Comment by StrathCole** [comment] 2024-09-17 05:57
@javiersuweijie it seems shuttle is missing some txs again. I have not researched all, but e.g. this one was reported 
https://etherscan.io/tx/0x8728ff36a23c7f69b0811706019dda9b0135d2454bc0e6d7ecc6eab348fb711d

**Comment by dinesh0304-2020** [comment] 2024-10-25 18:30
0x4e82be1a0ece659e06364fdcda1c5abc6465bcbcdb99fb5d96333dc7c9ba517e

https://etherscan.io/tx/0x4e82be1a0ece659e06364fdcda1c5abc6465bcbcdb99fb5d96333dc7c9ba517e

0xe9a9310478f4609a108d408ac0ba21e4514c9024e82efbe549853bf9a761c433

https://etherscan.io/tx/0xe9a9310478f4609a108d408ac0ba21e4514c9024e82efbe549853bf9a761c433

I bridged over to Terra Classic network from Ethereum but I did not receive LUNC coins. @StrathCole @javiersuweijie @devops-terra-money  kindly check and help.

Above are the transaction hashes.

**Comment by kianofedex** [comment] 2024-10-26 23:55
same here, help me please.
0x42336dce04294d91bdbcf8b05026f919543fd7e080fbe9b53b162ccc7bc4ce23
0x87cc62f7e44750711c0a17d9643744259a681c9acbaa3bfbaeacc823d7d70f4a
Bridged LUNC from ETH to Terra Classic and didn't receive coins.
 @StrathCole @javiersuweijie @devops-terra-money

**Comment by dinesh0304-2020** [comment] 2024-10-27 08:34
Guys, @kianofedex, 

There is an open issue and ensure to submit your details in the following post.

https://github.com/terra-money/shuttle/issues/108
